### ISSUE TITLE
[critical] build broken by `let` keyword

### ISSUE THREAD

**Issue by mlem** [visionmedia/debug#604] opened 2018-09-11 08:25 UTC
https://github.com/visionmedia/debug/commit/ba8a424d41e9dc6129e081ac3aa9715be6a45fbd introduced the let keyword breaks our build:
```
<our-path>/node_modules/karma/node_modules/http-proxy/node_modules/follow-redirects/node_modules/debug/src/node.js:132
09:17:34,371 WARN  -     let val = process.env[key];
09:17:34,371 WARN  -     ^^^
09:17:34,371 WARN  -
09:17:34,371 WARN  - SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by Qix-** [comment] 2018-09-11 08:29
Duplicate of #603.

Please look at the issues tracker in the future.

**Closed by Qix-** 2018-09-11 08:29 UTC
