### ISSUE TITLE
Can't Disable debug

### ISSUE THREAD

**Issue by ilyaigpetrov** [visionmedia/debug#495] opened 2017-08-30 17:05 UTC
https://runkit.com/ilyaigpetrov/59a6ef385d75ca0011ffb2c3
```js
const debug = require('debug')
console.log('ENABLED_1?', debug.enabled('*'));
debug.enable('*');
debug.disable('*');
console.log('ENABLED_2?', debug.enabled('*'));
```
Output:
```js
ENABLED_1?
true
ENABLED_2?
true
```

**Comment by thebigredgeek** [comment] 2017-09-04 23:15
@TooTallNate looks like we never fixed this :(

**Comment by bmacnaughton** [comment] 2017-10-19 14:08
It would be ideal to only disable the namespaces specified in the `debug.disable()` call.

**Comment by natew** [comment] 2017-11-14 17:09
I can't seem to disable it either... but it's hard to believe this is a real bug if only one person upvoted. Is there really no way to disable logs in browser? I've tried a lot of combinations, specific and wildcard, and it seems to never persists or disable any logging.

**Comment by Qix-** [comment] 2018-12-18 23:51
Confirmed still a bug in the latest version. See #425 as this will be fixed by that.

**Closed by Qix-** 2018-12-18 23:51 UTC
Labels: bug
