### ISSUE TITLE
links to the source code.

### ISSUE THREAD

**Issue by benmonro** [visionmedia/debug#229] opened 2015-10-01 16:34 UTC
This might be more of a question...

When I use console.log the chrome dev tools add a link to the line of code where that console.log statement was executed.  This makes it easy to jump to my code.  I'm wondering if there's any possible way to do this with debug().  Even if I have to manually print out a link that would be useful.

In my screenshot below, 1) is the console.log statement and 2) is the debug() statement.  1 will go to my code, 2 goes to the source code for debug which i don't want....

![image](https://cloud.githubusercontent.com/assets/399236/10226953/921bd55e-681f-11e5-9439-d0efd2f251af.png)

**Comment by ilearnio** [comment] 2015-10-14 19:50
+1 for implementing this feature for server debugging as well. There has to be some info about where the message came from, at least a file name and a line of code

**Comment by nullvariable** [comment] 2015-10-22 15:09
Looks like this is a duplicate of #198

**Comment by benmonro** [comment] 2015-10-22 15:12
no, not exactly.  In part there's the line number yes, but the important thing is that the console gives you a link directly to the code in the source view.

**Comment by nullvariable** [comment] 2015-10-22 15:17
Browser console or terminal console?

**Comment by benmonro** [comment] 2015-10-22 15:50
browser, that screenshot above is in the chrome dev tools console.  if you have a console.log() and a debug() statement you'll notice the difference.  there's an npm package called bows that acutally works correctly, but it ONLY works in the browser.  I'd prefer the debug() approach which works isomorphically...

**Comment by justrhysism** [comment] 2015-11-10 23:07
+1

**Comment by jwebcat** [comment] 2015-11-18 09:13
A simple solution to this without modifying library code for Chrome (can haz Firefox also), is to BlackBox the debug.js script and you will still get the debugging message but you will get the line number of the js it got called from not the same line 444 from debug.js where log() is defined.

Here is a good readme on how to BlackBox scripts in chrome devTools

https://developer.chrome.com/devtools/docs/blackboxing

- Here is a screenshot with debug working with namespaces reporting correct line numbers where it was called from.

<img width="817" alt="screenshot 2015-11-18 01 11 40" src="https://cloud.githubusercontent.com/assets/2264388/11236898/69577d70-8d91-11e5-8660-5c56d02ec055.png">

**Comment by diasdavid** [comment] 2016-01-07 16:08
Is there anything currently in the works to get this feature also in Node.js?

**Comment by thebigredgeek** [comment] 2016-12-14 22:53
closing this for now

**Closed by thebigredgeek** 2016-12-14 22:53 UTC
