### ISSUE TITLE
es6 "let " make uglify failed

### ISSUE THREAD

**Issue by Cyberpunkerplus** [visionmedia/debug#657] opened 2018-12-19 03:16 UTC
https://github.com/visionmedia/debug/blob/0e94034efb1e88b88a06ca3862d8d2cc2f2ed5d0/src/browser.js#L155

so, i find some changes in 4.1 version . Before , we use es5 style to define variabels, but in version 4.1, "var" turn to "let". some package require the debug pkg. when use uglify-js , it will throw errors, and it will not work in some platform like the browser those not support es6. 

well, i can use babel to transform the debug pkg, but i think the way is ugly.so, can we expose the es5 version in dist directory?

**Comment by Qix-** [comment] 2018-12-19 03:18
Duplicate of #604.

**Closed by Qix-** 2018-12-19 03:18 UTC
