### ISSUE TITLE
Debugging to file causes error

### ISSUE THREAD

**Issue by SidharthRaveendran** [visionmedia/debug#253] opened 2016-01-19 06:23 UTC
I'm facing the following error while trying to log to file, When i use set DEBUG=\* it shows debug on the console but nothing is written to the file.

Node on Windows with node version 5.1

E:\Sidharth>set DEBUG_FD=3 node app.js 3> whatever.log

E:\Sidharth>node app.js 3> whatever.log
E:\Sidharth\node_modules\debug\node.js:194
      throw new Error('Implement me. Unknown stream file type!');
      ^

Error: Implement me. Unknown stream file type!
    at createWritableStdioStream (E:\Sidharth\node_modules\debug\node.js:194:13)
    at Object.<anonymous> (E:\Sidharth\node_modules\debug\node.js:38:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\Sidharth\test.js:6:13)
    at Module._compile (module.js:425:26)

**Comment by mooyoul** [comment] 2016-04-08 21:42
It's not a bug. because [TTY mode not exists on Windows OS](https://en.wikipedia.org/wiki/Getty_(Unix)).

If you want to use logging to file using tty, you can use these methods:
1. Waits for Windows 10 bash support Release (currently in beta)
2. Move to POSIX system like Ubuntu, Mac OS X, Debian, etc, or installing it on Virtual Machine

.... or you can make your own logger instead of using `console.error` which is default bound.
```javascript
'use strict';

const
  fs    = require('fs'),
  util  = require('util'),
  debug = require('debug');

// cretes writeable log stream
const logStream = fs.createWriteStream('test2.log');

// overrides log function
debug.log = (...args) => {
  logStream.write(`${util.format.apply(null, args)}\n`);
};

// creates logger
const log = debug('wow');

log('foo');

log({
  wow: true,
  such: 'cool',
  awesome: 123
});

log('formatting? yes. %j', ['wow', 'such cool', 'awesome']);

setTimeout(function () {
  // don`t forget to close your stream!
  logStream.end();
}, 500);
```

<img width="552" alt="2016-04-09 6 38 49" src="https://cloud.githubusercontent.com/assets/2101743/14398290/f595d3e8-fe1d-11e5-97af-0da66e742770.png">

/ping @TooTallNate it would be nice if we document that tty is unsupported on Windows.

**Comment by thebigredgeek** [comment] 2016-12-14 22:41
Welcome a PR if any of you want to update the docs.  Closing this for now

**Closed by thebigredgeek** 2016-12-14 22:41 UTC
