### ISSUE TITLE
Why not include 'dist' folder in npm package?

### ISSUE THREAD

**Issue by stevenjlho** [visionmedia/debug#242] opened 2015-12-16 04:14 UTC
When i use webpack to compile file, console show these error message.

```
ERROR in debug (bower component)
Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/debug.js in /Users/stevenjlho/Work/v4s/htdocs/node_modules/debug
@ debug (bower component) 1:17-43
```

Npm package version is 2.2.0.

**Comment by strayiker** [comment] 2015-12-28 16:55
i have the same problem

**Comment by AndrejGajdos** [comment] 2015-12-30 17:34
+1

**Comment by TooTallNate** [comment] 2015-12-30 18:04
Is there a reason that webpack thinks its a bower component rather than an npm module?

**Comment by nathasm** [comment] 2016-01-05 21:23
I had to `npm install debug && cd debug && make` in order for the dist directory to show up. Not sure if that's by design or not.

**Comment by stephenmathieson** [comment] 2016-01-05 21:27
@TooTallNate probably the `bower.json` file

**Comment by TooTallNate** [comment] 2016-01-06 00:02
Maybe we just remove it?

**Comment by stephenmathieson** [comment] 2016-01-06 00:07
idk.. sounds like having bower support breaks webpack support.  i dont use either so i'd say remove all the things =)

**Comment by stevenjlho** [comment] 2016-01-06 05:57
Maybe I use [Bower Webpack Plugin](https://github.com/lpiepiora/bower-webpack-plugin), when I remove this plugin, console don't show error message.

**Comment by stepek** [comment] 2016-01-08 06:44
+1

**Comment by adamcharnock** [comment] 2016-01-12 10:04
Same problem here.

**Comment by nhaesler** [comment] 2016-01-17 18:32
Could you please publish a new release with the dist/ folder included? I can see that you disabled this in 43b0d51, but it is needed by everyone not using a module loader (or one, that is not compatible).

**Comment by gitsubham** [comment] 2016-01-19 06:15
+1

**Comment by nhaesler** [comment] 2016-01-19 11:35
@gitsubham Are you using Webpack too? It seems weird, that a npm package is recognized as a bower component. It looks like webpack supports all kinds of JS module formats, so you should be able to just include the browser.js in the package. With a module loader you should not need the dist/ folder.

As an alternative you could require my fork `https://github.com/nhaesler/debug.git#100cf7e`, so you'll get the dist/ folder, until my PR #251 is merged.

**Comment by huntout** [comment] 2016-01-25 10:17
How about appending  `bower.json` to `.npmignore`?

**Comment by stephenmathieson** [comment] 2016-01-27 17:59
> How about appending bower.json to .npmignore?

that makes sense to me

**Comment by cema-sp** [comment] 2016-02-01 15:42
@nathasm thank you, it worked out

**Comment by ShubhamGupta** [comment] 2016-08-12 08:50
For anyone using `bower-webpack-plugin`: The main issue is that it is recognizing the npm package as a bower component. This is because of this setting: `searchResolveModulesDirectories`. It is set to true by default and thus searches for the bower components in `resolve.modulesDirectories`. This probably points to your `node_modules` directory which is causing the plugin to see the npm package as a bower component. To resolve, simply set this as false in your webpack config. Hope this helps!

``` javascript

{
plugins: [new BowerWebpackPlugin({
      modulesDirectories: [path],
      manifestFiles:      "bower.json",
      includes:           /.*/,
      excludes:           [],
      searchResolveModulesDirectories: false
    })]
}
```

**Comment by HardlyMirage** [comment] 2016-09-05 11:40
No need to disable `searchResolveModulesDirectories`. Just add `node_modules` to the `excludes` array.

    plugins: [
        new BowerWebpackPlugin({ excludes: ['node_modules'] })
    ]

**Comment by crazyh** [comment] 2016-10-28 09:25
@ShubhamGupta, @HardlyMirage what if you want to install some Bower package with npm/yarn (so you do not want to exclude node_modules from BowerWebpackPlugin)?

For example: angular-bootstrap-toggle can be installed as Node-dependency but it does not use any module system because it just an Bower-package.

**Comment by thebigredgeek** [comment] 2016-12-14 22:43
Closing this for now.

**Closed by thebigredgeek** 2016-12-14 22:43 UTC
