### ISSUE TITLE
debug.enable() disabling previously enabled namespaces

### ISSUE THREAD

**Issue by tabcat** [visionmedia/debug#730] opened 2019-11-17 00:23 UTC
i'm having a some issues with enabling debug namespaces dynamically using debug.enable(). it seems that when i enable one thing and then enable something else, the first thing i enabled is no longer enabled? 
i've remedied this for now by enabling the root namespace with a wildcard and everything is fine.

heres some of the code
```js
const setLogOutputs = (self, scope, log) => {
  if (!log) {
    self.log = debug(scope)
    debug.enable(`${scope}*`) // DOING NOW
  } else {
    self.log = log.extend(scope)
  }
  self.log.error = self.log.extend('error')
  if (self.events) {
    self.log.log = (...p) => {
      try {
        self.events.emit('debug', ...p)
      } catch (e) { console.error(e) }
    }

    self.log.error.log = (...p) => {
      try {
        self.events.emit('error', ...p)
      } catch (e) { console.error(e) }
     debug.enable(`${self.log.namespace},${self.log.error.namespace}`) // DID BEFORE
    }
    self.events.on('error', console.log)
  }
}
```

**Comment by Qix-** [comment] 2019-11-17 02:08
Duplicate of #425.

**Closed by Qix-** 2019-11-17 02:08 UTC
