### ISSUE TITLE
FORCE_COLOR support

### ISSUE THREAD

**Issue by travi** [visionmedia/debug#566] opened 2018-05-01 20:16 UTC
even though `supports-color` is used in `debug`, it appears as though [`FORCE_COLOR`](https://github.com/chalk/supports-color#info) is not being honored. 

i'm getting color with no trouble when using with a script run directly (regardless of `FORCE_COLOR` being present or not), but lose the color output when using with a script run through [npm-run-all](https://github.com/mysticatea/npm-run-all), even with `FORCE_COLOR` enabled.

is this something specific about `debug`'s use of `supports-color`?

**Comment by LoganDark** [comment] 2018-06-16 05:47
> DEBUG_COLORS | Whether or not to use colors in the debug output.
> -- | --

[README.md](https://github.com/visionmedia/debug/blob/22f993216dcdcee07eb0601ea71a917e4925a30a/README.md)

**Comment by travi** [comment] 2018-06-19 02:20
@LoganDark i understand that there is a specific way to toggle colors for this library. however, i am not looking to force colors to be on for each individual library. part of the benefit of leveraging `supports-color` should be that the `FORCE_COLOR` convention is enabled pretty much automatically, or so i thought. i would prefer that `FORCE_COLOR` worked in this case than needing to enable yet another env var for color (especially for a single library)

**Comment by Qix-** [comment] 2018-06-19 08:17
Yes - you need to install `supports-color` alongside `debug` - it does not come shipped.

**Comment by travi** [comment] 2018-06-19 18:51
i have `supports-color` installed as a dependency of other cli tools and as a direct dependency. `npm ls supports-color` lists these from the other tools, as well as this line that shows my direct dependency: `├── supports-color@5.4.0 `.

again, color does work fine when running a script directly that leverages `debug`, but using `npm-run-all` with its `--print-label` flag loses color for `debug`. other cli tools that are using `chalk` do still output color in that situation when i set `FORCE_COLOR`, which aligns with what is mentioned [here](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#known-limitations). however, that does not work with `debug` for some reason.

**Comment by Qix-** [comment] 2018-06-20 17:49
Duplicate of #580 I think.

**Comment by Qix-** [comment] 2018-06-20 18:13
Going to chalk it up as such. Please let me know if that's not the case.

**Closed by Qix-** 2018-06-20 18:13 UTC
