### ISSUE TITLE
How to reproduce the pre-3.* behavior of debug.enable()?

### ISSUE THREAD

**Issue by therealgilles** [visionmedia/debug#552] opened 2018-03-05 09:02 UTC
Pre-3.*, debug.enable() did not override the previously set namespaces. This allowed to have debug.enable(namespace) in each file and enable/disable as needed on a per-file basis.

How can this behavior be reproduced with 3.* versions?

**Comment by Qix-** [comment] 2018-12-18 23:49
Duplicate of #425.

**Closed by Qix-** 2018-12-18 23:49 UTC
Labels: feature, question
