### ISSUE TITLE
Please fix the spell mistake in 2.4.0

### ISSUE THREAD

**Issue by hefangshi** [visionmedia/debug#347] opened 2016-12-14 06:56 UTC
https://github.com/visionmedia/debug/blob/master/debug.js#L126

https://travis-ci.org/fex-team/node-ral/jobs/183832044

**Comment by hereandnow** [comment] 2016-12-14 06:58
see my pull request ;-) https://github.com/visionmedia/debug/pull/349

this is really a problem right now

**Comment by JustFly1984** [comment] 2016-12-14 07:02
126:  debug.color = selectColor(namespae);
should be namespace

**Comment by dashmug** [comment] 2016-12-14 07:03
Yes, this is breaking many apps.

**Comment by budde377** [comment] 2016-12-14 07:03
How can this be released!
This should have been caught by a very simple static analysis!

**Comment by JustFly1984** [comment] 2016-12-14 07:03
please use eslint before deploy)

**Comment by knewter** [comment] 2016-12-14 07:03
Ha I just came here for the same reason.  Was recording a dailydrip episode when suddenly my build, which worked moments prior, was failing during the recording :)

**Comment by adamgoose** [comment] 2016-12-14 07:04
Geez, the timing!!! Same issue.

**Comment by knewter** [comment] 2016-12-14 07:04
@JustFly1984 maybe you could put together a PR that adds it as a pre-commit hook

**Comment by chrisatomix** [comment] 2016-12-14 07:04
Sending you a bill for $75 in lost earnings while troubleshooting 7 failed builds.

**Comment by thkdog** [comment] 2016-12-14 07:05
I've just google ERROR in namespae..... how could this be released...

**Comment by knewter** [comment] 2016-12-14 07:05
@chrisatomix maybe don't be an absolute jerk to someone who gave away his labor for free.  Did you pay him for the passing builds?

**Comment by JustFly1984** [comment] 2016-12-14 07:05
sorry I have my own things to do, and I don't know how to do PR yet, and currently have no time to learn that, altho you can just edit the module by yourself until it will be fixed by module owner

**Comment by dashmug** [comment] 2016-12-14 07:07
This is a problem because the NodeJS ecosystem allows automatic upgrades.

It's much easier in Python since dependencies are usually frozen.

**Comment by glebec** [comment] 2016-12-14 07:10
It astonishes me that a library downloaded ~7 million times per month has no test spec or even static analysis commit hook.

**Comment by knewter** [comment] 2016-12-14 07:11
@glebec send a PR - this wasn't malicious, but it sucks.  Imagine, though, if people only talked to you about your project when it broke their build.  yarn.lock would fix it, or pinning a version.  Have some empathy for the maintainers.

**Comment by knewter** [comment] 2016-12-14 07:11
For everyone that ends up here, pasting this from the fine folks at ember-cli on their issue tracking this:

## Mitigations

- Use yarn with a yarn.lock would have prevented this issue from affecting your project.
- Run `npm install --save-dev -E debug@2.3.3 && rm -rf node_modules && npm install` will force usage of a known working version in your app

**Comment by glebec** [comment] 2016-12-14 07:12
@knewter agreed on all counts — I'm not actually angry, just amazed.

**Comment by knewter** [comment] 2016-12-14 07:13
@glebec I just feel bad for him.  I was suggesting that you direct the amazed energy at a quick PR to help avoid the problems in the future too :)

**Comment by doublesharp** [comment] 2016-12-14 07:18
I created a module that leverages other modules to help maintain a good development environment, including automatically running npm scripts from git hooks (using git-validate). It will create these under ./git/hooks/pre-commit as well as place `.eslint` in the root and test directories. A script using the `depcheck` module leverages a `.depcheckrc` file for confirmation to make sure the dependencies in package.json line up to your project. 

```
npm i -D developer-tools

npm run depcheck
npm run validate
npm run lint
```

**Comment by halt-hammerzeit** [comment] 2016-12-14 07:26
This is rediculous!
Don't you have 100% coverage for such a commonly used npm module???

**Comment by Lellansin** [comment] 2016-12-14 07:27
Come on... it's breaking my work right now...

**Comment by ljharb** [comment] 2016-12-14 07:27
Please tone it down, everybody. Mistakes happen. It's been about 30-40 minutes, and it's being [worked on](https://twitter.com/thebigredgeek/status/808934737322672128) right now.

**Comment by thebigredgeek** [comment] 2016-12-14 07:27
Hey guys.  Apologies for the busted release.  We currently don't have static analysis or tests set up.  I've released 2.4.1 with a hotfix.  I agree it is ridiculous.  Currently adding test coverage and static analysis via eslint myself to make sure future releases don't shit the bed :)

**Comment by chrisatomix** [comment] 2016-12-14 07:28
I wasn't at all serious about the invoice, but we do currently have two developers assigned to investigate this internally.

Our `yarn.lock` file was supposed to install `2.3.3` during our CI/CD process, but for some reason it jumped to the broken `2.4.0` version. This highlights an issue with our build/deploy process rather than this package itself, broken releases are always a possibility but it shouldn't be possible to install a different version to Production than on a local Development environment.

I'm starting to wonder if it's a bug in Yarn itself. It's the end of the day here for us, and luckily none of our deploys were mission-critical (again, I was joking about the invoice). Hopefully this is resolved by tomorrow, otherwise we'll use one of the above workarounds (or lock down the debug.js version in `package.json` and switch back to `npm install`).

Also, hopefully this means automated testing can be added to this package to prevent these issues from occurring in future. There already seems to be some great suggestions above.

**Comment by navinpeiris** [comment] 2016-12-14 07:30
Just did an npm install, and all works fine now. Shit happens, thanks for the ultrafast fix up @thebigredgeek, @diedsmiling

**Comment by theredfoxfire** [comment] 2016-12-14 07:31
@chrisatomix don't worry dudes you are save 😄 you just forgot the emoticon

**Comment by nfroidure** [comment] 2016-12-14 07:31
Aha. Just facing the issue and it is already fixed :). Good job guys!

**Comment by kid-wumeng** [comment] 2016-12-14 07:32
now ok

**Comment by halt-hammerzeit** [comment] 2016-12-14 07:32
@thebigredgeek !["I saw what you did there" meme](http://i2.kym-cdn.com/photos/images/facebook/000/000/681/what-you-did-there-i-see-it.thumbnail.jpg)

**Comment by sushantdhiman** [comment] 2016-12-14 07:32
@2.4.1 Released :tada:

**Comment by dashmug** [comment] 2016-12-14 07:34
@chrisatomix It's not a problem with `yarn` nor your own CI/CD process. It's a general problem with the `npm` ecosystem because most dependencies of projects are dynamic.

In my case, it's not a direct dependency of my project. But it's a dependency of a dependency where we don't have control anymore.

**Comment by doublesharp** [comment] 2016-12-14 07:34
@chrisatomix it broke my build too, but I really can't figure out how - as far as I can tell everything (including dependencies) is locked to 2.3.3.

**Comment by dashmug** [comment] 2016-12-14 07:35
@thebigredgeek Thank you very much for the quick response and the fix.

**Closed by doublesharp** 2016-12-14 07:34 UTC

**Comment by zoltan-nz** [comment] 2016-12-14 07:36
@thebigredgeek thanks for the quick fix, and thank You and @TooTallNate for Your hard work. This kind of little mistakes make us better, so don't worry too much about it. Please keep up the great work, we really appreciate it. :)

**Comment by koresar** [comment] 2016-12-14 07:36
That's an awesome thread people :)
Thanks @thebigredgeek for your hard work!

Merry Xmas :)

**Comment by JoshSmith** [comment] 2016-12-14 07:36
🎉  Huge thanks to everyone who jumped on this so quickly. Your efforts are much appreciated.

**Comment by chancancode** [comment] 2016-12-14 07:36
@chrisatomix @doublesharp are you installing yarn using npm? yarn itself depends on `debug` so it you aren't using the pre-packaged builds then that's probably your issue: https://github.com/yarnpkg/yarn/blob/master/package.json#L15

**Comment by thebigredgeek** [comment] 2016-12-14 07:37
@koresar not me.  Thanks to everyone who put in PRs.  All I had to do was hit the merge button, run a sanity check, and publish haha.

**Comment by thebigredgeek** [comment] 2016-12-14 07:38
With regards to yarn, I highly recommend installing via yum/homebrew/apt-get.  You'll have a better experience

**Comment by chrisatomix** [comment] 2016-12-14 07:40
@chancancode I think you've nailed it, we assumed it was because of a browsersync dependency. Didn't realise this package was also used by Yarn itself! Definitely need to switch to pre-packaged builds.

@thebigredgeek Great advice :+1: This typo might turn out to be a blessing in disguise if it makes our builds more robust :)

**Comment by SallyOne** [comment] 2016-12-14 07:41
害苦我了

**Comment by awestroke** [comment] 2016-12-14 07:43
This is a good wake up call to start using [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) or [yarn](https://yarnpkg.com/)

**Comment by thebigredgeek** [comment] 2016-12-14 07:45
Glad this shit show can be a learning lesson for some of us haha

**Comment by doublesharp** [comment] 2016-12-14 07:55
@chancancode I'm not using `yarn`, this is an `express` app.

**Comment by KunalKapadia** [comment] 2016-12-14 08:04
@chrisatomix Are you using yarn in production ?
[#761](https://github.com/yarnpkg/yarn/issues/761) is still open, which doesn't install correct dependencies on using `--production` flag.
So does your production build include dev dependencies ?

cc: @thebigredgeek @awestroke

**Comment by thebigredgeek** [comment] 2016-12-14 08:19
https://github.com/visionmedia/debug/commit/dafc99b98cf52212aed816bb5d4671de9f1a63b6 < in case anyone is interested, boilerplate for tests, linting, and v3 roadmap (ES2015 + full test coverage) has been added.  Waiting on admin access to integrate with circle ci :)

**Comment by chrisatomix** [comment] 2016-12-14 08:19
@KunalKapadia Using it on our CI/CD server to compile CSS/JS files, if the build is successful then it deploys to Production. We don't actually use Yarn on our Production servers themselves. Also, all our dependencies are specified as dev dependencies, so I don't think that open issue would affect us anyway.

**Comment by doublesharp** [comment] 2016-12-14 08:32
@thebigredgeek I just sent a PR that duplicates some of what you did and includes a few other things that might be useful, feel free to use as you please. Thanks!

**Comment by thebigredgeek** [comment] 2016-12-14 08:37
@doublesharp thanks will look into it when I get some free time.  Currently sick, so deploying tonight probably wasn't a great choice on my part

**Comment by thebigredgeek** [comment] 2016-12-14 08:51
@halt-hammerzeit lol

**Comment by FeliciousX** [comment] 2016-12-14 09:13
thank you for the quick fix <3

**Comment by codeaholics** [comment] 2016-12-14 10:03
@doublesharp don't grep package.json, do `npm ls debug`

**Comment by doublesharp** [comment] 2016-12-14 10:34
@codeaholics Sorry, I wasn't totally clear, I did that, and *then* I grep'd just to double check. Everything is either 2.2.0 or 2.3.3, so I'm not sure what was grabbing the latest version of `debug`.

```
npm ls debug
├─┬ bcrypt@1.0.1
│ └─┬ node-pre-gyp@0.6.30
│   └─┬ tar-pack@3.1.4
│     └── debug@2.2.0 
├─┬ body-parser@1.15.2
│ └── debug@2.2.0 
├─┬ compression@1.6.2
│ └── debug@2.2.0 
├── debug@2.3.3 
├─┬ developer-tools@0.0.9
│ ├─┬ mocha@3.2.0
│ │ └── debug@2.2.0 
│ └─┬ nodemon@1.11.0
│   └─┬ chokidar@1.6.1
│     └─┬ fsevents@1.0.15
│       └─┬ node-pre-gyp@0.6.29
│         └─┬ tar-pack@3.1.4
│           └── debug@2.2.0 
├─┬ eslint-plugin-import@2.2.0
│ └─┬ eslint-module-utils@2.0.0
│   └── debug@2.2.0 
├─┬ express@4.14.0
│ ├── debug@2.2.0 
│ ├─┬ finalhandler@0.5.0
│ │ └── debug@2.2.0 
│ └─┬ send@0.14.1
│   └── debug@2.2.0 
├─┬ morgan@1.7.0
│ └── debug@2.2.0 
└─┬ sqlite3@3.1.8
  └─┬ node-pre-gyp@0.6.31
    └─┬ tar-pack@3.3.0
      └── debug@2.2.0 
```

**Comment by codeaholics** [comment] 2016-12-14 10:41
Interesting. As others have pointed out, Yarn uses (perhaps directly, perhaps transitively) debug. I know you said you aren't using Yarn, but I just checked, and so does NPM - although latest (4.0.3) still only appears to bring in debug 2.2.0. It seems like there's a difference between the versions of the tools (or the NPM config?) being used between your laptop and your CI server. 

Either way, I'm guessing you're all sorted now any way.

**Comment by doublesharp** [comment] 2016-12-14 10:47
@codeaholics It's all working again, but definitely confusing. FWIW - the version of node and npm is the same, and the Jenkins server deletes the workspace and installs node locally for each build... I actually just reinstalled both from scratch a few days ago so I'm certain this is the case. The only difference is my laptop is a Mac and Jenkins is on CentOS7.

**Comment by yamikuronue** [comment] 2016-12-14 12:24
@thebigredgeek Let me know if you want some help setting up CI. It'll save your bacon in cases like this, and I am a QA professional by day as well as my company's build engineer, so I'm willing to offer what assistance I can. The SockDrawer team really appreciates the Debug library :) I'd love to help give something back

**Comment by SpainTrain** [comment] 2016-12-14 15:06
Folks who mentioned spending time tracking down a broken dependency - you should give https://greenkeeper.io/ a shot.  It creates a branch to run CI for every update to every one of your first-order dependencies.  Since we started using it, we have not once had to track down which dep broke our build (e.g., I came in this morning and already knew debug had broken a couple projects :smile_cat:)

/CC @chrisatomix

**Comment by tj** [comment] 2016-12-14 18:09
To the entitled people: donate some money, then maybe people will have more time to devote to the free software that you use every day.

**Comment by doublesharp** [comment] 2016-12-14 18:31
Contributing to the project or just being gracious won't hurt either.

On Dec 14, 2016 10:09 AM, "TJ Holowaychuk" <notifications@github.com> wrote:

To the entitled people: donate some money, then maybe people will have more
time to devote to the free software that you use every day.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/visionmedia/debug/issues/347#issuecomment-267109014>,
or mute the thread

**Comment by JoshSmith** [comment] 2016-12-14 18:53
To follow up on what @tj said, you can read about just how one-sided and broken this situation is in Nadia Eghbal's report, _[Roads and Bridges](http://www.fordfoundation.org/library/reports-and-studies/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure)_.

If you want to help fix this problem, some thoughts:

- Donate money to projects, for example [the ones on Open Collective](https://opencollective.com/opensource)
- Submit a pull request
  - This time of year you can use [24 Pull Requests](https://24pullrequests.com/)
  - Find some issues on [CodeTriage](https://www.codetriage.com/)
  - Find some issues with [First Timers Only](http://www.firsttimersonly.com/)
  - Every month we post a ["Who needs contributors?" thread on HN](https://news.ycombinator.com/item?id=12847045)
- Ask maintainers if you can help triage issues
- As @doublesharp said: at the minimum, just show some empathy
- Push back against demanding or entitled people, but also help them to understand just how broken OSS is for maintainers

And though I'm biased, keep an eye on https://github.com/code-corps, too, to find ways to help. Clearly the contributor funnel is broken. We also need to be kinder. Do what you can to help fix it.

**Comment by thebigredgeek** [comment] 2016-12-14 19:07
I honestly don't hold it against anyone here who was upset by the broken release.  The industry itself is way more high stress than it should be, with engineers working under constant pressure for 60+ hours a week and their jobs always threatened by unreasonable managers.  So when a package like this breaks they flip out.  I think it has less to do with OSS being broken for maintainers and more to do with the industry as a whole being dysfunctional and that dysfunction cascading into OSS

**Comment by tj** [comment] 2016-12-14 19:08
That too, industry is a mess!

**Comment by yamikuronue** [comment] 2016-12-14 19:37
Agreed. Lecturing people on github issues isn't any way to enact real change.

**Comment by thebigredgeek** [comment] 2016-12-14 19:48
@yamikuronue if you wanna submit a PR to add coveralls integration and coverage reporting with our existing mocha tooling, it would be much appreciated :)

**Comment by doublesharp** [comment] 2016-12-14 22:43
@codeaholics @chancancode @chrisatomix 

I figured out how I was getting the latest version and @dashmug is correct that it is caused by [semantic versioning/semver](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004). Using `npm ls debug` shows the required versions, but when you grep the `package.json` file you see that many of them are included as `"debug": "^2.3.3"`. The caret will result in it using the latest available version that is less than "3.0.0", so when "2.4.0" was released `npm` used it as an acceptable version.

Using `"debug": "2.3.3"` would lock it to that version, but a lot of widely used modules use a caret range, like [`superagent`](https://github.com/visionmedia/superagent/blob/master/package.json#L29) (which is a dependency of [`supertest`](https://github.com/visionmedia/supertest/blob/master/package.json#L11)), which is being used to run tests on my Jenkins server.

**Comment by chrisatomix** [comment] 2016-12-14 22:59
@doublesharp In our case it was Yarn which was installing 2.4.0, due to this line:
 `"debug": "^2.2.0",`
If we'd been using the precompiled version of Yarn instead of running `npm install -g yarn` our builds wouldn't have failed.

The irony is that it turned out our CI provider already includes Yarn in their default image! We didn't realise they'd added it last month, so we were able to remove the install command from our build script. It shaved about 10 seconds off our average build time :)

Like I said, this error might be a blessing in disguise. Especially now that everyone has realised how much of a critical component it is in so many other packages, the developer may get more support than he ever anticipated. It might even encourage the Facebook Yarn team to go through all their dependencies and make sure each one has automated testing in place.

**Comment by thebigredgeek** [comment] 2016-12-14 23:08
Looking for more input on V3 here: https://github.com/visionmedia/debug/issues/370

**Comment by doublesharp** [comment] 2016-12-14 23:24
@chrisatomix For sure, I never knew about `npm shrinkwrap` to lock all the dependencies to a particular version until it occurred to me how `npm install` was handling the semantic versioning. To be honest I never really thought that much about how it worked previously. I'm planning to generate an `npm-shrinkwrap.json` and manage the versions manually for anything critical - which is good knowledge to gain from a few failed builds :)

**Comment by codeaholics** [comment] 2016-12-15 09:05
@doublesharp the doco for npm ls says:

> This  command  will  print  to stdout all the versions of packages that are installed, as well as their dependencies, in a tree-structure.

If you're saying it just prints the required version, and not actually the installed version, then that seems pretty broken to me!

**Comment by doublesharp** [comment] 2016-12-15 19:08
@codeaholics You're right, there must be something screwy with my project. I just created a test project, installed supertest, and it correctly shows the installed version of debug and not the caret range. Not sure why it was showing the old versions for me (especially considering I deleted `node_modules` and rebuilt them... I've since actually upgraded debug, so I'm giving up trying to figure out what was going on. :/
