### ISSUE TITLE
namespace is not defined

### ISSUE THREAD

**Issue by raulggonzalez** [visionmedia/debug#357] opened 2016-12-14 07:20 UTC
From `2.4.0`, I am receiving:

```
ReferenceError: namespae is not defined
    at createDebug (/home/me/Projects/Justo/Justo.js/Justo.jsg/justo-generator-horizon/node_modules/debug/debug.js:126:29)
    at Object.<anonymous> (/home/me/Projects/Justo/Justo.js/Justo.jsg/justo-generator-horizon/node_modules/babel-traverse/lib/path/index.js:47:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/me/Projects/Justo/Justo.js/Justo.jsg/justo-generator-horizon/node_modules/babel-traverse/lib/index.js:10:13)
```

npm ls:

```
me@boxer:~/Projects/Justo/Justo.js/Justo.jsg/justo-generator-horizon$ npm ls debug
justo-generator-horizon@0.1.0 /home/me/Projects/Justo/Justo.js/Justo.jsg/justo-generator-horizon
└─┬ justo-plugin-babel@0.3.0
  └─┬ babel-core@6.20.0
    └── debug@2.4.0 

me@boxer:~/Projects/Justo/Justo.js/Justo.jsg/justo-generator-horizon$
```

**Comment by rwjblue** [comment] 2016-12-14 07:23
Duplicate of #347

**Closed** 2016-12-14 07:28 UTC
