### ISSUE TITLE
Dynamic debug enable fails in node packages

### ISSUE THREAD

**Issue by tfermm** [visionmedia/debug#691] opened 2019-02-28 18:24 UTC
When using knex and another node library I was unable to change the status of the debugger in the global scope and have it change the debuging in a module.

Here is my test file

```node
const debug = require('debug');
const config = require('./config.json');

var knex = require('knex')({
  client: 'mysql',
  connection: {
    host : config.sql.host,
    user : config.sql.user,
    password : config.sql.password,
    database : config.sql.database
  }
});

debug.enable('knex:*');

knex.raw('show databases').then(function(res){
	console.log('Done');
});
```
If I run this code with 
```
node test.js
```
All I see in console is "Done"
```
$ node test.js
Done
```
However if I run the code with 
```
DEBUG=knex:* node test.js
```
I get the debug response I'm expecting
```
$ DEBUG=knex:* node test.js
  knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query show databases undefined +0ms
  knex:bindings [] undefined +0ms
  knex:client releasing connection to pool: __knexUid1 +6ms
Done
```

Also if you move 
```
debug.enable('knex:*');
```
To be above the require for knex it will also log as expected.

It looks like the required node module will take on the debug state when the library is required and not when the debug log call is made.

**Comment by Qix-** [comment] 2019-03-01 06:22
Yes, `.enable()` is very much not intuitive (mostly because it's an anti-pattern, and thus makes things complex and even leaks memory). It's documented as such in the various issues here in the repository and is on the list to be fixed.

You *should* be using `debug` with environment variables, however. That is the proper way to use it.

**Comment by Qix-** [comment] 2019-03-01 06:22
Closing as a duplicate of the many other `.enable()`-related tickets already open in the tracker.

**Closed** 2019-03-01 06:22 UTC
